Metrics/MethodLength:
  Max: 7
Style/ParallelAssignment:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/AbcSize:
  Max: 18
Lint/HandleExceptions:
  Enabled: false
Metrics/BlockLength:
  Enabled: false